### ISSUE TITLE
Split remote logs per function, not host

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-rsyslog#6]
Currently the log server puts logs into /var/log/remote/servers/%hostname%.log. This is not good.

There's just too many files. Hard to keep track of, and probably inefficient for the log daemon to write all over the disk too. Add in rotated logs too, and the result is:

<pre><code>
]# ls -1 /var/log/remote/servers/|wc -l
12466
</code></pre>

I think it would be better to split the logs based on function, similar to the usual local logging. E.g. something like
- /var/log/remote/secure (auth messages for all hosts)
- /var/log/remote/slurm.log (slurm logs from all hosts)
- ... etc.
- /var/log/remote/messages (everything else)

(See also the usual "cattle vs. pets" stuff for further arguments why this is better than per-host logs)

(Longer term, we should maybe think about pushing the logs into elasticsearch+kibana to have some way of analyzing what's actually happening.)

**Comment by martbhell** [comment]
Progress on this in #7 thanks.
For the second thing - elasticsearch + kibana. I put it up as another topic for the ansible workshop.  I already have playbooks for an ELK machine.

**Comment by jabl** [comment]
https://github.com/CSC-IT-Center-for-Science/ansible-role-rsyslog/pull/7 is merged, closing.
